INFO     2020-10-27 00:31:16,864 logger_01.py         Line:[117:] Start
ERROR    2020-10-27 00:31:16,864 logger_01.py         Line:[118:] Something may be fail.
ERROR    2020-10-27 00:31:16,864 logger_01.py         Line:[125:] fail to get result...
Traceback (most recent call last):
  File "D:/Git/learngit/module_study/study_logger»’÷æ/logger_01.py", line 122, in traceback
    result = 10 / 0
ZeroDivisionError: division by zero
INFO     2020-10-27 00:31:16,864 logger_01.py         Line:[126:] Finished
